# Generated by Django 3.1.4 on 2020-12-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201210_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='title',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=256),
        ),
    ]
